public class Frontier_VisitList {
   public String Name;
    public List<Event> eventList;
   public String Id;
   public String Type;
   public String RADL_Class;
   Public Date ActivityDate;
   public String CreatedBy;
   public String SAPId; 
   public String Country_Name;
    public String District_Name;
    public String TerritoryId;
    public String TerritoryLabel;
 
    public Frontier_VisitList(){}
}