/* 
*
* @author : Cognizant technology solutions.
* @version : 1.0
* @objects Referenced : Events
* @Description :  This is the wrapper class for account controller
*/
public class Frontier_TouchPoints {
    public Integer No_Of_TouchPoints;
    public String Name;
    public String RADL_Class;
    public String Type;
    public String BillingStreet;
    public Integer No_Of_Opportunities;
    public String Business_Role;
    public String Street_Address;
    public String City_Name;
    public String State_Name;
    public String Country_Name;
    public String accountGMEResponseWrapper;
    
public Frontier_TouchPoints(){}
}